version: '3.8'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge